### PR TITLE
Enhancement/use hpp for headers based on PR https://github.com/moveit/moveit2/pull/3113

### PR DESCRIPTION
**Pull request by CihatAltiparmak**
### Description

Addresses #994 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/moveit/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by mikeferguson** [comment]
Looks like CI is failing because @sea-bass maybe did a force push to his branch of ros2_kortex?

**Comment by mikeferguson** [comment]
Also - we aren't going to want to merge this until we get the headers actually released onto the binaries (humble is out, Jazzy sync looks to be happening next monday? not sure about rolling)

**Comment by CihatAltiparmak** [comment]
I agree with you because, as i mentioned, i have to fix documentation so that documentation can show the best practices to new users.

**Comment by sea-bass** [comment]
> Looks like CI is failing because @sea-bass maybe did a force push to his branch of ros2_kortex?

I definitely did do that. Many times.

**Comment by sea-bass** [comment]
> > What's the best way to resolve this?
> 
> I think we need to rebuild the tutorial docker image - they automatically rebuild on Sunday morning I think, I'm not sure how to trigger it manually...

Ah yes, this is done through the moveit repo actions. I'm on it.

**Review by sea-bass — APPROVED** [review]
Given both Jazzy and Rolling branches of MoveIt 2 have .hpp files, I am OK approving this as is.

**Comment by mikeferguson** [comment]
> Given both Jazzy and Rolling branches of MoveIt 2 have .hpp files, I am OK approving this as is.

Just a note that Jazzy debs aren't out yet with those headers (ETA monday according to ROS discourse)

**Comment by sea-bass** [comment]
Yeah we can wait.

I didn't release Rolling by the way... so those binaries won't work next sync unless we do.

**Comment by mikeferguson** [comment]
> I didn't release Rolling by the way... so those binaries won't work next sync unless we do.

Rolling has 2.12.0 in testing, but not yet sync'd (we just didn't put 2.12.1 in, which includes the fix for checkstartstate)

**Comment by sea-bass** [comment]
Right. I should know better. Never mind!

**Comment by CihatAltiparmak** [comment]
Hi @sea-bass , I have also updated documentation manually. I think we should wait until merging corresponding PR in moveit_visual_tools. Thus we can early detect potential issues in this PR. The documentation doesn't consist of source codes.

**Comment by sea-bass** [comment]
Sounds good. If you can tag me in the other related PRs when ready for review, I'll take a look.

But for sure let's merge after the Jazzy sync.

Also, for those other repos that may not have distinct branches between humble and later, there are conditional includes we can add -- like was done in moveit2.

**Comment by sea-bass** [comment]
Jazzy sync is in -- shall we merge this?

**Comment by CihatAltiparmak** [comment]
I've updated my branch, this will build package without cache. Let's see if there is any warning in CI. And then good to roll ahead.

**Pull request merged**
