### PR TITLE
Use fork of `ros2_kortex` that does not depend on Gazebo classic

### PR DESCRIPTION
**Pull request by sea-bass**
### Description

In Ubuntu 24.04, Gazebo classic is no longer supported or available from binaries. Due to the `ros2_kortex` repo still using this as a dependency, CI has been failing.

See: https://github.com/Kinovarobotics/ros2_kortex/issues/217 and https://github.com/Kinovarobotics/ros2_kortex/pull/228

So, to have this work, we (and all consumers of this package on Jazzy onwards) have to get around this.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/moveit/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by sea-bass** [comment]
@henningkayser where do these dependencies come from? I added to the `.repos` file and it still is failing to be picked up. Does it come from the `moveit2` repo? If so, it's weird to have to add the dependencies there...

**Comment by sea-bass** [comment]
Ugh, no, this then has even more transitive dependencies on `gazebo_ros` and `gazebo_dev` which are not available on Ubuntu 24.04. This will not be a viable option, and instead it's preferable to fix the `ros2_kortex` repo.

I tried doing that, but the maintainers seem reluctant: https://github.com/Kinovarobotics/ros2_kortex/pull/228

**Comment by sea-bass** [comment]
This is now failing because the version of `ros2_control` from binaries doesn't match the latest `gz_ros2_control` ... I give up for now, too many breakages.

**Review by stephanie-eng — COMMENTED** [review]
For what it's worth, I tried adding ros2_control as a source-built dependency on top of your branch, but it looks like robotiq_driver is not compatible with the latest ros2_control:
https://github.com/stephanie-eng/moveit2_tutorials/actions/runs/9884753382/job/27301653148

I'm also waving the white flag on this for now, so I figured I'd share my findings to whomever tries this again.

**Comment by henningkayser** [comment]
Thank you for your effort! I started a similar thing already here #913. Unfortunately, there is currently just not enough capacity to properly tackle the tutorial issues. I'll still pin this as high priority until we can assign someone to get this fixed.

**Comment by sea-bass** [comment]
> For what it's worth, I tried adding ros2_control as a source-built dependency on top of your branch, but it looks like robotiq_driver is not compatible with the latest ros2_control: https://github.com/stephanie-eng/moveit2_tutorials/actions/runs/9884753382/job/27301653148
> 
> I'm also waving the white flag on this for now, so I figured I'd share my findings to whomever tries this again.

I actually also fixed the robotiq package...

https://github.com/PickNikRobotics/ros2_robotiq_gripper/pull/54

We basically need that landed, a new ros2_control sync or source build, and the same fix for moveit_resources:

https://github.com/moveit/moveit_resources/pull/200

Believe me, I tried...

**Comment by stephanie-eng** [comment]
Well, the rolling sync is done, so we shouldn't need a ros2_control source build... That's one thing out of the way.

**Comment by stephanie-eng** [comment]
We failed again due to an invalid parameter (`sim_ignition`). I think it's due to a stray `sim_ignition` passed into the gripper xacro ([this guy](https://github.com/sea-bass/ros2_kortex/blob/remove-gazebo-classic/kortex_description/grippers/robotiq_2f_85/urdf/robotiq_2f_85_macro.xacro#L30C9-L30C24)), where you have since been renamed it to `sim_gazebo` ([here](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/main/robotiq_description/urdf/robotiq_2f_85_macro.urdf.xacro#L8)).

**Comment by sea-bass** [comment]
> We failed again due to an invalid parameter (`sim_ignition`). I think it's due to a stray `sim_ignition` in ros2_kortex passed into the gripper xacro ([this guy](https://github.com/sea-bass/ros2_kortex/blob/remove-gazebo-classic/kortex_description/grippers/robotiq_2f_85/urdf/robotiq_2f_85_macro.xacro#L30C9-L30C24)), where you have since been renamed it to `sim_gazebo` ([here](https://github.com/PickNikRobotics/ros2_robotiq_gripper/blob/main/robotiq_description/urdf/robotiq_2f_85_macro.urdf.xacro#L8)).
> 
> @sea-bass it's your fork, so you get to be the arbiter if the above is correct or not.

You got it!

When I first put up the `ros2_kortex` PR I told myself I wouldn't mess with any other repos in the process, but then I found I had to for the numerous reasons in this thread... so I ended up changing the Robotiq repo after all!

**Comment by sea-bass** [comment]
So the next issue is that the old bringup test is trying to launch RViz that that node is crashing on the CI runner... is this a new thing?

**Comment by sea-bass** [comment]
IT PASSED!!!!!!!!!!

**Review by stephanie-eng — APPROVED** [review]

**Pull request merged**
